### ISSUE TITLE
Access to HR-services (minwintid.adeo.no + agresso.adeo.no)

### ISSUE THREAD

**Issue by jhrv** [nais/device#86] opened 2020-07-12 11:10 UTC

**Comment by toby1knby** [comment] 2020-10-12 16:57
Duplicate of #142

**Comment by sechmann** [comment] 2020-10-28 10:16
Need BigIP APM exception for these (Terje)

**Comment by jhrv** [comment] 2020-11-20 08:49
is this really a duplicate? Isn't it better to open directly to the service through the gateway like we do for the other services? (e.g. logs.adeo.no) @toby1knby

**Comment by sechmann** [comment] 2022-02-28 08:01
done

**Closed as completed by sechmann** 2022-02-28 08:01 UTC
Labels: enhancement, preserve
